server:
   port: 80
   context-path: /
mybatis:
   configuration:
# 开启驼峰uName自动映射到u_name
      map-underscore-to-camel-case: true
spring:
# mysql
   datasource:
      url: jdbc:mysql://localhost:3306/heartdata
      username: root
      password: qianhao123
      driver-class-name: com.mysql.jdbc.Driver